services:
  onec-server:
    image: onec-server:${ONEC_VERSION}
    container_name: onec-server
    restart: always
    depends_on:
      - postgres
    network_mode: host
    # networks:
    #   - private
    # ports:
    #   - "1541"
    #   - "1540"
    #   - "1560-1591"
  postgres:
    image: rsyuzyov/docker-postgresql-pro-1c
    container_name: postgresql-pro-1c
    restart: always
    network_mode: host
#     networks:
#       - private
# networks:
#   private:
#     driver: bridge