name: Загрузка расширения
description: Загрузка расширения в информационную базу с использованием ibcmd
inputs:
  name:
    description: 'Имя загружаемого расширения'
    required: true
  path:
    description: 'Путь к файлу расширения'
    required: true
runs:
  using: "composite"
  steps:
    - name: Загрузка расширения ${{inputs.name}}
      shell: bash
      run: |
        ibcmd infobase config load --db-path=file-db --extension=${{inputs.name}} --force ${{inputs.path}}
        ibcmd infobase config apply --db-path=file-db --extension=${{inputs.name}} --force
        ibcmd infobase config extension update --db-path=file-db --name=${{inputs.name}} --safe-mode=no --unsafe-action-protection=no
